export const MRT_Localization_UZ = {
  actions: "",
  and: "va",
  cancel: "Bekor qilish",
  changeFilterMode: "Filtr rejimini o'zgartirish",
  changeSearchMode: "Qidiruv rejimini o'zgartirish",
  clearFilter: "Filtrni tozalash",
  clearSearch: "Qidiruvni tozalash",
  clearSort: "Tartibni tozalash",
  clickToCopy: "Nusxa olish uchun bosing",
  columnActions: "Ustun harakati",
  copiedToClipboard: "Buferga nusxalandi",
  collapse: "Yopish",
  collapseAll: "Barchasini yopish",
  dropToGroupBy: "{column} ustuniga qo'shish",
  edit: "Tahrirlash",
  expand: "Ochish",
  expandAll: "Barchasini ochish",
  filterArrIncludes: "Yoqish",
  filterArrIncludesAll: "Barshasini yoqish",
  filterArrIncludesSome: "Yoqish",
  filterBetween: "Orasida",
  filterBetweenInclusive: "Inklyuziv o'rtasida",
  filterByColumn: "{column} bo'yicha filtrlash",
  filterContains: "O'z ichiga oladi",
  filterEmpty: "Bo'sh",
  filterEndsWith: "Tugaydi",
  filterEquals: "Teng",
  filterEqualsString: "Teng",
  filterFuzzy: "Fizzi",
  filterGreaterThan: "Katta",
  filterGreaterThanOrEqualTo: "Katta yoki teng",
  filterInNumberRange: "Orasida",
  filterIncludesString: "O'z ichiga oladi",
  filterIncludesStringSensitive: "Tarkibida (katta-kichik harf)",
  filterLessThan: "Kichik",
  filterLessThanOrEqualTo: "Kichik yoki teng",
  filterMode: "Filtr rejimi: {filterType}",
  filterNotEmpty: "Bo'sh emas",
  filterNotEquals: "Teng emas",
  filterStartsWith: "Bundan boshlanadi",
  filterWeakEquals: "Tend",
  filteringByColumn: "{column} bo'yicha filtrlash - {filterType} {filterValue}",
  goToFirstPage: "Birinchi sahifaga o'tish",
  goToLastPage: "Oxirgi sahifaga o'tish",
  goToNextPage: "Keyingi sahifaga o'tish",
  goToPreviousPage: "Oldingi sahifaga o'tish",
  grab: "Ushlash",
  groupByColumn: "{column} bo'yicha guruhlash",
  groupedBy: "Guruhlash",
  hideAll: "Barchasini berkitish",
  hideColumn: "{column} ustunini berkitish",
  max: "Maks.",
  min: "Min.",
  move: "Ko'chirish",
  noRecordsToDisplay: "Ma'lumotlar topilmadi",
  noResultsFound: "Hech qanday natija topilmadi",
  of: "dan",
  or: "yoki",
  pinToLeft: "Chapga biriktirish",
  pinToRight: "O'ngga biriktirish",
  resetColumnSize: "Ustun o'lchamini tiklash",
  resetOrder: "Tartibni tiklash",
  rowActions: "Qator harakatlari",
  rowNumber: "#",
  rowNumbers: "Qatorlar soni",
  rowsPerPage: "Har bir sahifaga qatorlar",
  save: "Saqlash",
  search: "Qidirish",
  selectedCountOfRowCountRowsSelected:
    "{rowCount} tadan {selectedCount} ta qator tanlandi",
  select: "Tanlash",
  showAll: "Barchasini ko'rsatish",
  showAllColumns: "Barcha ustunlarni ko'rsatish",
  showHideColumns: "Ustunlarni ko'rsatish/yashirish",
  showHideFilters: "Filtrlarni ko'rsatish/yashirish",
  showHideSearch: "Qidiruvni ko'rsatish/yashirish",
  sortByColumnAsc: "{column} ortish bo'yicha tartiblash",
  sortByColumnDesc: "{column} kamayish bo'yicha tartiblash",
  sortedByColumnAsc: "{column} ortishi boʻyicha tartiblash",
  sortedByColumnDesc: "{column} kamayish bo'yicha tartiblash",
  thenBy: ", keyin ",
  toggleDensity: "Zichlinki o'zgartirish",
  toggleFullScreen: "To'liq ekran rejimini yoqish",
  toggleSelectAll: "Hammasini tanlash",
  toggleSelectRow: "Qator tanlashni almashtirish",
  toggleVisibility: "Ko'rinishni o'zgartirish",
  ungroupByColumn: "{column} bo'yicha guruhdan ajratish",
  unpin: "Olib tashlash",
  unpinAll: "Hammasini olib tashlash",
  unsorted: "Tartiblanmagan",
  print: "Chop etish",
};
